# Use the official Node.js image as the base image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the entire project to the working directory
COPY . .

# Build the Next.js application
RUN npm run build

# Set environment variables
# ENV NODE_ENV=3000

# Expose the port that your Next.js app is running on (usually 3000)
EXPOSE 3000

# Command to start the Next.js app
CMD ["npm", "run", "dev"]
